<?php

namespace Database\Seeders;

use App\Models\Content;
use Illuminate\Database\Seeder;

class ContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            // blog
            [
                'title' => 'Krisis Air di DAS Citarum: Investigasi Lapangan',
                'slug' => 'krisis-air-citarum',
                'body' => 'Investigasi mendalam mengenai pencemaran air di Daerah Aliran Sungai Citarum...',
                'tags' => 'air, citarum, polusi',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2025-06-01',
                'category' => 'blog',
            ],
            [
                'title' => 'Deforestasi Masif di Pegunungan Halimun',
                'slug' => 'deforestasi-halimun',
                'body' => 'Laporan penebangan hutan liar yang merusak ekosistem Pegunungan Halimun...',
                'tags' => 'hutan, deforestasi',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2025-05-15',
                'category' => 'blog',
            ],
            [
                'title' => 'Menagih Janji Reklamasi Tambang',
                'slug' => 'reklamasi-tambang',
                'body' => 'Analisis komitmen perusahaan tambang dalam melakukan reklamasi lahan pasca-tambang...',
                'tags' => 'tambang, reklamasi',
                'status' => 'draft',
                'image_url' => '',
                'publish_date' => null,
                'category' => 'blog',
            ],
            // regulasi
            [
                'title' => 'UU No. 32 Tahun 2009 — Perlindungan Lingkungan Hidup',
                'slug' => 'uu-32-2009',
                'body' => 'Undang-Undang Republik Indonesia Nomor 32 Tahun 2009 tentang Perlindungan dan Pengelolaan Lingkungan Hidup...',
                'tags' => 'undang-undang',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2009-10-03',
                'category' => 'regulasi',
            ],
            [
                'title' => 'PP No. 22 Tahun 2021 — Penyelenggaraan Perlindungan Lingkungan',
                'slug' => 'pp-22-2021',
                'body' => 'Peraturan Pemerintah Nomor 22 Tahun 2021 tentang Penyelenggaraan Perlindungan dan Pengelolaan Lingkungan Hidup...',
                'tags' => 'peraturan pemerintah',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2021-02-02',
                'category' => 'regulasi',
            ],
            // siaran-pers
            [
                'title' => 'WALHI Jabar Menolak Izin Tambang di Kawasan Lindung Cianjur',
                'slug' => 'tolak-tambang-cianjur',
                'body' => 'Pernyataan sikap WALHI Jawa Barat menolak keras rencana izin usaha pertambangan...',
                'tags' => 'tambang, siaran pers',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2025-06-20',
                'category' => 'siaran-pers',
            ],
            [
                'title' => 'WALHI Jabar Mendesak Penghentian Total Tambang Ilegal di Gunung Halimun',
                'slug' => 'desak-henti-tambang-halimun',
                'body' => 'WALHI Jawa Barat mendesak Pemerintah Provinsi dan aparat penegak hukum untuk segera menghentikan total seluruh aktivitas pertambangan ilegal di kawasan Gunung Halimun yang telah merusak lebih dari 200 hektar hutan lindung.',
                'tags' => 'siaran pers, tambang, kehutanan',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2026-05-22',
                'category' => 'siaran-pers',
            ],
            [
                'title' => 'Kemenangan Petani Garut: Bukti Pentingnya Advokasi Hukum untuk Keadilan Agraria',
                'slug' => 'kemenangan-petani-garut',
                'body' => 'Putusan Pengadilan Negeri Garut yang memenangkan gugatan 300 keluarga petani menjadi preseden penting dalam perjuangan keadilan agraria di Jawa Barat. WALHI akan terus mendampingi masyarakat yang kehilangan tanah.',
                'tags' => 'siaran pers, agraria, hukum',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2026-05-16',
                'category' => 'siaran-pers',
            ],
            [
                'title' => 'Data Mengkhawatirkan: Pencemaran Citarum Meningkat 23% dalam Semester I 2026',
                'slug' => 'pencemaran-citarum-meningkat-2026',
                'body' => 'Hasil monitoring WALHI Jabar menunjukkan peningkatan drastis tingkat pencemaran Sungai Citarum. Kami menuntut pemerintah melakukan tindakan tegas terhadap pabrik-pabrik yang membuang limbah ke sungai.',
                'tags' => 'siaran pers, air, citarum, limbah',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2026-05-11',
                'category' => 'siaran-pers',
            ],
            // infografis
            [
                'title' => 'Peta Konflik Agraria Jawa Barat 2024',
                'slug' => 'peta-konflik-agraria-2024',
                'body' => 'Visualisasi data sebaran titik konflik agraria di wilayah Jawa Barat selama tahun 2024...',
                'tags' => 'agraria, peta',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2024-12-01',
                'category' => 'infografis',
            ],
            [
                'title' => 'Jejak Pertambangan Ilegal di Jawa Barat',
                'slug' => 'jejak-tambang-ilegal-jabar',
                'body' => 'Visualisasi data sebaran lokasi dan dampak aktivitas pertambangan ilegal di wilayah Jawa Barat.',
                'tags' => 'tambang, jabar, infografis',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2026-05-22',
                'category' => 'infografis',
            ],
            [
                'title' => 'Dampak Pencemaran Citarum terhadap Kesehatan',
                'slug' => 'dampak-pencemaran-citarum',
                'body' => 'Visualisasi data tingkat pencemaran Sungai Citarum dan korelasinya terhadap kesehatan masyarakat sekitar.',
                'tags' => 'air, citarum, kesehatan, infografis',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2026-05-16',
                'category' => 'infografis',
            ],
            [
                'title' => 'Deforestasi Jawa Barat 2020-2025',
                'slug' => 'deforestasi-jabar-2020-2025',
                'body' => 'Visualisasi laju kehilangan tutupan hutan di wilayah Jawa Barat sepanjang periode 2020 hingga 2025.',
                'tags' => 'hutan, deforestasi, jabar, infografis',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2026-05-11',
                'category' => 'infografis',
            ],
            // kertas-posisi
            [
                'title' => 'Posisi WALHI terhadap RUU Pertanahan',
                'slug' => 'posisi-ruu-pertanahan',
                'body' => 'Kertas posisi resmi WALHI Jawa Barat memberikan rekomendasi kritis atas draf RUU Pertanahan...',
                'tags' => 'agraria, posisi',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2025-03-10',
                'category' => 'kertas-posisi',
            ],
            // newsletter
            [
                'title' => 'E-Newsletter WALHI Jabar — Edisi Juni 2025',
                'slug' => 'newsletter-juni-2025',
                'body' => 'Berita-berita lingkungan hidup terkini di Jawa Barat edisi Juni 2025...',
                'tags' => 'newsletter',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2025-06-30',
                'category' => 'newsletter',
            ],
            // buletin-bumi
            [
                'title' => 'Buletin Bumi Vol. 12 — Keadilan Iklim',
                'slug' => 'buletin-bumi-vol-12',
                'body' => 'Buletin Bumi edisi volume ke-12 fokus pada isu Keadilan Iklim dan dampaknya di daerah...',
                'tags' => 'buletin, iklim',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2025-05-01',
                'category' => 'buletin-bumi',
            ],
            // jurnal
            [
                'title' => 'Jurnal Tanah Air — Edisi Khusus Citarum',
                'slug' => 'jurnal-citarum',
                'body' => 'Kumpulan jurnal ilmiah populer tentang restorasi dan sejarah ekologi sungai Citarum...',
                'tags' => 'jurnal, citarum',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2025-04-01',
                'category' => 'jurnal',
            ],
            // laporan-tahunan
            [
                'title' => 'Laporan Tahunan WALHI Jawa Barat 2025',
                'slug' => 'laporan-tahunan-2025',
                'body' => '{"subtitle":"Melawan Eksploitasi, Membangun Kedaulatan Rakyat","stats":["289 Kasus Kerusakan Lingkungan Ditangani","45 Advokasi Hukum Didampingi","18 Kampanye Besar Dilaksanakan","12.450 Masyarakat Terlibat Langsung"],"pages":"156 Halaman","downloads":"3.2K Downloads"}',
                'tags' => 'laporan, tahunan, 2025',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2025-12-31',
                'category' => 'laporan-tahunan',
            ],
            [
                'title' => 'Laporan Tahunan WALHI Jawa Barat 2024',
                'slug' => 'laporan-tahunan-2024',
                'body' => '{"subtitle":"Tahun Perjuangan Keadilan Ekologis","stats":["267 Kasus Ditangani","38 Advokasi Hukum","15 Kampanye Dilaksanakan","10.200 Masyarakat Terlibat"],"pages":"142 Halaman","downloads":"4.1K Downloads"}',
                'tags' => 'laporan, tahunan, 2024',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2024-12-31',
                'category' => 'laporan-tahunan',
            ],
            [
                'title' => 'Laporan Tahunan WALHI Jawa Barat 2023',
                'slug' => 'laporan-tahunan-2023',
                'body' => '{"subtitle":"Resistensi Rakyat terhadap Krisis Ekologis","stats":["241 Kasus Ditangani","32 Advokasi Hukum","12 Kampanye Dilaksanakan","8.500 Masyarakat Terlibat"],"pages":"128 Halaman","downloads":"2.8K Downloads"}',
                'tags' => 'laporan, tahunan, 2023',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2023-12-31',
                'category' => 'laporan-tahunan',
            ],
            // donasi
            [
                'title' => 'Kampanye Selamatkan Citarum',
                'slug' => 'kampanye-citarum',
                'body' => 'Target: Rp 50.000.000. Donasi akan dialokasikan untuk pemantauan kualitas air dan edukasi warga DAS...',
                'tags' => 'donasi, citarum',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2025-01-01',
                'category' => 'donasi',
            ],
            // pekan-rakyat
            [
                'title' => 'Pekan Rakyat Lingkungan Hidup 2025',
                'slug' => 'pekan-rakyat-2025',
                'body' => 'Bandung, 15–20 Agustus 2025. Rangkaian pameran foto, diskusi publik, dan festival seni...',
                'tags' => 'event, pekan rakyat',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2025-08-15',
                'category' => 'pekan-rakyat',
            ],
            // sejarah
            [
                'title' => 'Sejarah WALHI Jawa Barat',
                'slug' => 'sejarah',
                'body' => 'WALHI Jawa Barat berdiri pada tahun 1990 sebagai respons atas meningkatnya konflik lingkungan...',
                'tags' => 'sejarah',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '1990-01-01',
                'category' => 'sejarah',
            ],
            // visi-misi
            [
                'title' => 'Visi dan Misi WALHI Jabar',
                'slug' => 'visi-misi',
                'body' => 'Visi: Terwujudnya tatanan sosial, ekonomi, dan politik yang adil serta demokratis yang menjamin hak rakyat atas lingkungan hidup...',
                'tags' => 'visi, misi',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2024-01-01',
                'category' => 'visi-misi',
            ],
            // kontak
            [
                'title' => 'Informasi Kontak WALHI Jabar',
                'slug' => 'kontak',
                'body' => "alamat: Jl. Simponi No.29, Turangga, Kec. Lengkong, Kota Bandung, Jawa Barat 40264\nwhatsapp: +62 821-1982-1159\nemail: walhijabar@gmail.com\nfacebook: https://facebook.com/walhi.jabar\ninstagram: https://instagram.com/walhi.jabar\nyoutube: https://www.youtube.com/@walhijabar",
                'tags' => 'kontak',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2024-01-01',
                'category' => 'kontak',
            ],
            // statistik
            [
                'title' => 'Kasus Ditangani',
                'slug' => 'kasus-ditangani',
                'body' => '2,847',
                'tags' => 'Icon-10.svg',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2025-01-01',
                'category' => 'statistik',
            ],
            [
                'title' => 'Keluarga Terdampak',
                'slug' => 'keluarga-terdampak',
                'body' => '15,000+',
                'tags' => 'Icon-11.svg',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2025-01-01',
                'category' => 'statistik',
            ],
            [
                'title' => 'Tingkat Keberhasilan',
                'slug' => 'tingkat-keberhasilan',
                'body' => '85%',
                'tags' => 'Icon-12.svg',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2025-01-01',
                'category' => 'statistik',
            ],
            [
                'title' => 'Laporan Investigasi',
                'slug' => 'laporan-investigasi',
                'body' => '150+',
                'tags' => 'Icon-13.svg',
                'status' => 'published',
                'image_url' => '',
                'publish_date' => '2025-01-01',
                'category' => 'statistik',
            ],
            // isu-kritis
            [
                'title' => 'Pertambangan Ilegal',
                'slug' => 'pertambangan-ilegal-isu',
                'body' => 'Ratusan titik tambang ilegal di Jawa Barat merusak hutan, air, dan ruang hidup masyarakat.',
                'tags' => '200+ Titik',
                'status' => 'published',
                'image_url' => 'causes-1-1.jpg',
                'publish_date' => '2025-01-01',
                'category' => 'isu-kritis',
            ],
            [
                'title' => 'Deforestasi',
                'slug' => 'deforestasi-isu',
                'body' => 'Alih fungsi hutan untuk perkebunan dan properti menggerus tutupan hijau dan memicu bencana ekologis.',
                'tags' => '15.000 Ha/Tahun',
                'status' => 'published',
                'image_url' => 'causes-1-2.jpg',
                'publish_date' => '2025-01-01',
                'category' => 'isu-kritis',
            ],
            [
                'title' => 'Pencemaran Sungai',
                'slug' => 'pencemaran-sungai-isu',
                'body' => 'Limbah industri dan rumah tangga mencemari sungai-sungai utama serta mengancam kesehatan warga.',
                'tags' => '75% Tercemar',
                'status' => 'published',
                'image_url' => 'causes-1-3.jpg',
                'publish_date' => '2025-01-01',
                'category' => 'isu-kritis',
            ],
            [
                'title' => 'Konflik Agraria',
                'slug' => 'konflik-agraria-isu',
                'body' => 'Ribuan keluarga petani kehilangan tanah akibat perampasan lahan dan proyek skala besar.',
                'tags' => '2.500+ Kasus',
                'status' => 'published',
                'image_url' => 'causes-1-4.jpg',
                'publish_date' => '2025-01-01',
                'category' => 'isu-kritis',
            ],
            [
                'title' => 'Krisis Iklim',
                'slug' => 'krisis-iklim-isu',
                'body' => 'Banjir bandang, kekeringan ekstrem, dan cuaca tak menentu semakin sering melanda Jawa Barat.',
                'tags' => '+2.5°C Target',
                'status' => 'published',
                'image_url' => 'causes-1-5.jpg',
                'publish_date' => '2025-01-01',
                'category' => 'isu-kritis',
            ],
        ];

        foreach ($data as $item) {
            Content::updateOrCreate(
                ['slug' => $item['slug']],
                $item
            );
        }
    }
}
