<footer style="align-self: stretch; height: 689px; padding-top: 4px; padding-left: 95px; padding-right: 95px; background: #1D1D1D; border-top: 4px #F4F1EA solid; flex-direction: column; justify-content: flex-start; align-items: flex-start; display: flex;">
    <div style="align-self: stretch; height: 685px; padding-top: 64px; padding-left: 32px; padding-right: 32px; flex-direction: column; justify-content: flex-start; align-items: flex-start; gap: 48px; display: flex;">
        <div style="align-self: stretch; height: 260px; position: relative;">
            <div style="width: 584px; height: 260px; left: 0; top: 0; position: absolute;">
                <div style="width: 584px; height: 48px; left: 0; top: 0; position: absolute;">
                    <div style="left: 0; top: -0.5px; position: absolute; color: #F4F1EA; font-size: 32px; font-family: Bebas Neue, sans-serif; font-weight: 400; text-transform: uppercase; line-height: 48px; letter-spacing: 1.6px; word-wrap: break-word;">WALHI Jawa Barat</div>
                </div>
                <div style="width: 584px; height: 81.59px; left: 0; top: 64px; position: absolute;">
                    <div style="width: 584px; left: 0; top: -0.5px; position: absolute; color: #F4F1EA; font-size: 16px; font-family: Inter, sans-serif; font-weight: 400; line-height: 27.2px; word-wrap: break-word;">Wahana Lingkungan Hidup Indonesia (WALHI) Jawa Barat adalah organisasi lingkungan hidup independen yang memperjuangkan keadilan ekologis dan kedaulatan rakyat atas sumber daya alam.</div>
                </div>
                <div style="width: 584px; height: 48px; left: 0; top: 169.59px; position: absolute; display: inline-flex; justify-content: flex-start; align-items: flex-start; gap: 16px;">
                    <div style="width: 48px; height: 48px; padding-top: 14px; padding-bottom: 2px; padding-left: 14px; padding-right: 14px; background: #256D4A; outline: 2px #256D4A solid; outline-offset: -2px; flex-direction: column; justify-content: flex-start; align-items: flex-start; display: inline-flex;"><div style="align-self: stretch; height: 20px; position: relative; overflow: hidden;"><div style="width: 9.17px; height: 16.67px; left: 5.83px; top: 1.67px; position: absolute; outline: 1.67px #F4F1EA solid; outline-offset: -0.83px;"></div></div></div>
                    <div style="width: 48px; height: 48px; padding-top: 14px; padding-bottom: 2px; padding-left: 14px; padding-right: 14px; background: #256D4A; outline: 2px #256D4A solid; outline-offset: -2px; flex-direction: column; justify-content: flex-start; align-items: flex-start; display: inline-flex;"><div style="align-self: stretch; height: 20px; position: relative; overflow: hidden;"><div style="width: 16.67px; height: 14.17px; left: 1.67px; top: 3.33px; position: absolute; outline: 1.67px #F4F1EA solid; outline-offset: -0.83px;"></div></div></div>
                    <div style="width: 48px; height: 48px; padding-top: 14px; padding-bottom: 2px; padding-left: 14px; padding-right: 14px; background: #256D4A; outline: 2px #256D4A solid; outline-offset: -2px; flex-direction: column; justify-content: flex-start; align-items: flex-start; display: inline-flex;"><div style="align-self: stretch; height: 20px; position: relative; overflow: hidden;"><div style="width: 16.67px; height: 16.67px; left: 1.67px; top: 1.67px; position: absolute; outline: 1.67px #F4F1EA solid; outline-offset: -0.83px;"></div><div style="width: 6.67px; height: 6.67px; left: 6.7px; top: 6.63px; position: absolute; outline: 1.67px #F4F1EA solid; outline-offset: -0.83px;"></div></div></div>
                    <div style="width: 48px; height: 48px; padding-top: 14px; padding-bottom: 2px; padding-left: 14px; padding-right: 14px; background: #256D4A; outline: 2px #256D4A solid; outline-offset: -2px; flex-direction: column; justify-content: flex-start; align-items: flex-start; display: inline-flex;"><div style="align-self: stretch; height: 20px; position: relative; overflow: hidden;"><div style="width: 16.71px; height: 11.78px; left: 1.65px; top: 4.11px; position: absolute; outline: 1.67px #F4F1EA solid; outline-offset: -0.83px;"></div><div style="width: 4.17px; height: 5px; left: 8.33px; top: 7.5px; position: absolute; outline: 1.67px #F4F1EA solid; outline-offset: -0.83px;"></div></div></div>
                </div>
            </div>
            <div style="width: 268px; height: 260px; left: 632px; top: 0; position: absolute; flex-direction: column; justify-content: flex-start; align-items: flex-start; gap: 16px; display: inline-flex;">
                <div style="align-self: stretch; height: 40px; position: relative; border-bottom: 2px #256D4A solid;"><div style="left: 0; top: 0; position: absolute; color: #5C8D59; font-size: 20px; font-family: Bebas Neue, sans-serif; font-weight: 400; text-transform: uppercase; line-height: 30px; letter-spacing: 1px; word-wrap: break-word;">Navigasi</div></div>
                <div style="align-self: stretch; height: 204px; flex-direction: column; justify-content: flex-start; align-items: flex-start; gap: 12px; display: flex;">
                    <div style="align-self: stretch; height: 24px; position: relative;"><div style="left: 0; top: 0; position: absolute; color: #F4F1EA; font-size: 15px; font-family: Inter, sans-serif; font-weight: 400; line-height: 22.5px; word-wrap: break-word;">Tentang Kami</div></div>
                    <div style="align-self: stretch; height: 24px; position: relative;"><div style="left: 0; top: 0; position: absolute; color: #F4F1EA; font-size: 15px; font-family: Inter, sans-serif; font-weight: 400; line-height: 22.5px; word-wrap: break-word;">Isu Lingkungan</div></div>
                    <div style="align-self: stretch; height: 24px; position: relative;"><div style="left: 0; top: 0; position: absolute; color: #F4F1EA; font-size: 15px; font-family: Inter, sans-serif; font-weight: 400; line-height: 22.5px; word-wrap: break-word;">Kampanye</div></div>
                    <div style="align-self: stretch; height: 24px; position: relative;"><div style="left: 0; top: 0; position: absolute; color: #F4F1EA; font-size: 15px; font-family: Inter, sans-serif; font-weight: 400; line-height: 22.5px; word-wrap: break-word;">Berita &amp; Artikel</div></div>
                    <div style="align-self: stretch; height: 24px; position: relative;"><div style="left: 0; top: 0; position: absolute; color: #F4F1EA; font-size: 15px; font-family: Inter, sans-serif; font-weight: 400; line-height: 22.5px; word-wrap: break-word;">Laporan</div></div>
                    <div style="align-self: stretch; height: 24px; position: relative;"><div style="left: 0; top: 0; position: absolute; color: #F4F1EA; font-size: 15px; font-family: Inter, sans-serif; font-weight: 400; line-height: 22.5px; word-wrap: break-word;">Kontak</div></div>
                </div>
            </div>
            <div style="width: 268px; height: 260px; left: 948px; top: 0; position: absolute; flex-direction: column; justify-content: flex-start; align-items: flex-start; gap: 16px; display: inline-flex;">
                <div style="align-self: stretch; height: 40px; position: relative; border-bottom: 2px #256D4A solid;"><div style="left: 0; top: 0; position: absolute; color: #5C8D59; font-size: 20px; font-family: Bebas Neue, sans-serif; font-weight: 400; text-transform: uppercase; line-height: 30px; letter-spacing: 1px; word-wrap: break-word;">Jaringan</div></div>
                <div style="align-self: stretch; height: 192px; flex-direction: column; justify-content: flex-start; align-items: flex-start; gap: 12px; display: flex;">
                    <div style="align-self: stretch; height: 24px; position: relative;"><div style="left: 0; top: 0; position: absolute; color: #F4F1EA; font-size: 15px; font-family: Inter, sans-serif; font-weight: 400; line-height: 22.5px; word-wrap: break-word;">WALHI Nasional</div></div>
                    <div style="align-self: stretch; height: 24px; position: relative;"><div style="left: 0; top: 0; position: absolute; color: #F4F1EA; font-size: 15px; font-family: Inter, sans-serif; font-weight: 400; line-height: 22.5px; word-wrap: break-word;">Friends of the Earth</div></div>
                    <div style="align-self: stretch; height: 24px; position: relative;"><div style="left: 0; top: 0; position: absolute; color: #F4F1EA; font-size: 15px; font-family: Inter, sans-serif; font-weight: 400; line-height: 22.5px; word-wrap: break-word;">Greenpeace Indonesia</div></div>
                    <div style="align-self: stretch; height: 48px; position: relative;"><div style="width: 268px; left: 0; top: 0; position: absolute; color: #F4F1EA; font-size: 15px; font-family: Inter, sans-serif; font-weight: 400; line-height: 22.5px; word-wrap: break-word;">KPA (Konsorsium Pembaruan Agraria)</div></div>
                    <div style="align-self: stretch; height: 24px; position: relative;"><div style="left: 0; top: 0; position: absolute; color: #F4F1EA; font-size: 15px; font-family: Inter, sans-serif; font-weight: 400; line-height: 22.5px; word-wrap: break-word;">JATAM (Jaringan Advokasi Tambang)</div></div>
                </div>
            </div>
        </div>
        <div style="align-self: stretch; height: 146px; padding-top: 36px; padding-bottom: 4px; padding-left: 36px; padding-right: 36px; background: #256D4A; outline: 4px #256D4A solid; outline-offset: -4px; flex-direction: column; justify-content: flex-start; align-items: flex-start; display: flex;">
            <div style="align-self: stretch; height: 74px; justify-content: space-between; align-items: center; display: inline-flex;">
                <div style="width: 736px; height: 74px; flex-direction: column; justify-content: flex-start; align-items: flex-start; gap: 8px; display: inline-flex;">
                    <div style="align-self: stretch; height: 42px; position: relative;"><div style="left: 0; top: 0; position: absolute; color: #F4F1EA; font-size: 28px; font-family: Bebas Neue, sans-serif; font-weight: 400; text-transform: uppercase; line-height: 42px; letter-spacing: 1.4px; word-wrap: break-word;">Berlangganan Newsletter</div></div>
                    <div style="align-self: stretch; height: 24px; position: relative;"><div style="left: 0; top: -1px; position: absolute; color: #F4F1EA; font-size: 16px; font-family: Inter, sans-serif; font-weight: 400; line-height: 24px; word-wrap: break-word;">Dapatkan update terbaru tentang isu lingkungan, kampanye, dan aksi-aksi WALHI Jawa Barat.</div></div>
                </div>
                <div style="width: 384px; height: 52px; position: relative;">
                    <div style="width: 241.75px; height: 52px; left: 0; top: 0; position: absolute;">
                        <div style="width: 241.75px; height: 52px; padding-top: 12px; padding-bottom: 12px; padding-left: 48px; padding-right: 16px; left: 0; top: 0; position: absolute; background: white; overflow: hidden; outline: 2px #F4F1EA solid; outline-offset: -2px; justify-content: flex-start; align-items: center; display: inline-flex;"><div style="color: rgba(29, 29, 29, 0.50); font-size: 16px; font-family: Inter, sans-serif; font-weight: 400; word-wrap: break-word;">Email kamu</div></div>
                        <div style="width: 18px; height: 18px; left: 16px; top: 17px; position: absolute; overflow: hidden;"><div style="width: 15px; height: 12px; left: 1.5px; top: 3px; position: absolute; outline: 1.5px #5C8D59 solid; outline-offset: -0.75px;"></div><div style="width: 15px; height: 4.5px; left: 1.5px; top: 5.25px; position: absolute; outline: 1.5px #5C8D59 solid; outline-offset: -0.75px;"></div></div>
                    </div>
                    <div style="width: 134.25px; height: 52px; left: 249.75px; top: 0; position: absolute; background: #D95C3F; outline: 2px #D95C3F solid; outline-offset: -2px;"><div style="left: 26px; top: 15.5px; position: absolute; text-align: center; color: #F4F1EA; font-size: 14px; font-family: Inter, sans-serif; font-weight: 700; text-transform: uppercase; line-height: 21px; letter-spacing: 0.35px; word-wrap: break-word;">Subscribe</div></div>
                </div>
            </div>
        </div>
        <div style="align-self: stretch; height: 55px; padding-top: 34px; border-top: 2px #256D4A solid; flex-direction: column; justify-content: flex-start; align-items: flex-start; display: flex;">
            <div style="align-self: stretch; height: 21px; justify-content: space-between; align-items: center; display: inline-flex;">
                <div style="width: 688.34px; height: 21px; position: relative;"><div style="left: 0; top: 0; position: absolute; color: #F4F1EA; font-size: 14px; font-family: Inter, sans-serif; font-weight: 400; line-height: 21px; word-wrap: break-word;">© 2026 WALHI Jawa Barat. Organisasi Independen. Tidak Berafiliasi dengan Korporasi atau Pemerintah.</div></div>
                <div style="width: 283.85px; height: 18px; justify-content: flex-start; align-items: flex-start; gap: 24px; display: flex;">
                    <div style="width: 123.25px; height: 18px; position: relative;"><div style="left: 0; top: 0.5px; position: absolute; color: #F4F1EA; font-size: 12px; font-family: Inter, sans-serif; font-weight: 600; text-transform: uppercase; line-height: 18px; letter-spacing: 0.30px; word-wrap: break-word;">Kebijakan Privasi</div></div>
                    <div style="flex: 1 1 0; height: 18px; position: relative;"><div style="left: 0; top: 0.5px; position: absolute; color: #F4F1EA; font-size: 12px; font-family: Inter, sans-serif; font-weight: 600; text-transform: uppercase; line-height: 18px; letter-spacing: 0.30px; word-wrap: break-word;">Transparansi Dana</div></div>
                </div>
            </div>
        </div>
    </div>
</footer>
